[package]
entry = "src/main.fuse"
app = "Api"
backend = "native"

[build]
openapi = "build/openapi.json"

[serve]
static_dir = "."
static_index = "index.html"

[assets]
css = "assets/css/style.css"
watch = true
