services:
  docs:
    image: fuse-docs:pre-alpha
    build:
      context: ..
      dockerfile: docs/Dockerfile
    ports:
      - "4080:4080"
    environment:
      PORT: "4080"
      FUSE_HOST: "0.0.0.0"
