[package]
name = "fuse"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "1.3"
fuse-rt = { path = "../fuse-rt" }
fusec = { path = "../fusec" }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
